apiVersion: v1
kind: Service
metadata:
  name: widgetario-web-lb
  labels:
    kubernetes.courselabs.co: hackathon
    app: widgetario
spec:
  ports:
    - port: 8080
      targetPort: http
  selector:  
    app: widgetario
    component: web
  type: LoadBalancer # type of service ... to be exposed to the internet
---
apiVersion: v1
kind: Service
metadata:
  name: widgetario-web-np
  labels:
    kubernetes.courselabs.co: hackathon
    app: widgetario
spec:
  ports:
    - port: 8080
      targetPort: http
      nodePort: 30008
  selector:
    app: widgetario
    component: web
  type: NodePort # type of service