apiVersion: v1
kind: Service
metadata:
  name: widgetario-web-lb
  labels:
    kubernetes.courselabs.co: hackathon
    app: widgetario
spec:
  ports:
  - port: 8080
    targetPort: http
  selector:
    app: widgetario
    component: web
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: widgetario-web-np
  labels:
    app: widgetario
spec:
  ports:
  - port: 8080
    targetPort: http
  selector:
    app: widgetario
    component: web
  type: NodePort