apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
  labels:
    kubernetes.courselabs.co: hackathon
    app: widgetario
spec:
  selector:
    matchLabels:
        app: widgetario
        component: products-db
  template:
    metadata:
      labels: 
        app: widgetario
        component: products-db
        hackathon: part-1
    spec:
      containers:
        - name: app
          image: widgetario/products-db:21.03
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: products-db-password