apiVersion: v1
kind: Secret
metadata:
  name: stock-api-connection
  labels:
    kubernetes.courselabs.co: hackathon
type: Opaque
stringData:
  POSTGRES_CONNECTION_STRING: "postgres://postgres:passwd1234@products-db:5432/products?sslmode=disable"